// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: launchpad.proto

package launchpad

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Launchpad_Health_FullMethodName              = "/launchpad.Launchpad/Health"
	Launchpad_GetConfig_FullMethodName           = "/launchpad.Launchpad/GetConfig"
	Launchpad_ListLaunchpads_FullMethodName      = "/launchpad.Launchpad/ListLaunchpads"
	Launchpad_CreateLaunchpad_FullMethodName     = "/launchpad.Launchpad/CreateLaunchpad"
	Launchpad_GetLaunchpad_FullMethodName        = "/launchpad.Launchpad/GetLaunchpad"
	Launchpad_ListLaunchpadTokens_FullMethodName = "/launchpad.Launchpad/ListLaunchpadTokens"
	Launchpad_ListTokens_FullMethodName          = "/launchpad.Launchpad/ListTokens"
	Launchpad_GetToken_FullMethodName            = "/launchpad.Launchpad/GetToken"
	Launchpad_GetTransaction_FullMethodName      = "/launchpad.Launchpad/GetTransaction"
	Launchpad_PrepareLaunch_FullMethodName       = "/launchpad.Launchpad/PrepareLaunch"
	Launchpad_QuoteSwap_FullMethodName           = "/launchpad.Launchpad/QuoteSwap"
	Launchpad_PrepareSwap_FullMethodName         = "/launchpad.Launchpad/PrepareSwap"
	Launchpad_PrepareFeeClaim_FullMethodName     = "/launchpad.Launchpad/PrepareFeeClaim"
	Launchpad_GetFees_FullMethodName             = "/launchpad.Launchpad/GetFees"
	Launchpad_CreateAuthChallenge_FullMethodName = "/launchpad.Launchpad/CreateAuthChallenge"
	Launchpad_VerifyAuthSignature_FullMethodName = "/launchpad.Launchpad/VerifyAuthSignature"
)

// LaunchpadClient is the client API for Launchpad service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LaunchpadClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConfigResponse, error)
	ListLaunchpads(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListLaunchpadsResponse, error)
	CreateLaunchpad(ctx context.Context, in *CreateLaunchpadRequest, opts ...grpc.CallOption) (*LaunchpadInfo, error)
	GetLaunchpad(ctx context.Context, in *GetLaunchpadRequest, opts ...grpc.CallOption) (*LaunchpadInfo, error)
	ListLaunchpadTokens(ctx context.Context, in *ListLaunchpadTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error)
	ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*Token, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	PrepareLaunch(ctx context.Context, in *PrepareLaunchRequest, opts ...grpc.CallOption) (*PreparedTransaction, error)
	QuoteSwap(ctx context.Context, in *QuoteSwapRequest, opts ...grpc.CallOption) (*QuoteSwapResponse, error)
	PrepareSwap(ctx context.Context, in *PrepareSwapRequest, opts ...grpc.CallOption) (*PreparedTransaction, error)
	PrepareFeeClaim(ctx context.Context, in *PrepareFeeClaimRequest, opts ...grpc.CallOption) (*PreparedTransaction, error)
	GetFees(ctx context.Context, in *GetFeesRequest, opts ...grpc.CallOption) (*GetFeesResponse, error)
	CreateAuthChallenge(ctx context.Context, in *CreateAuthChallengeRequest, opts ...grpc.CallOption) (*CreateAuthChallengeResponse, error)
	VerifyAuthSignature(ctx context.Context, in *VerifyAuthSignatureRequest, opts ...grpc.CallOption) (*VerifyAuthSignatureResponse, error)
}

type launchpadClient struct {
	cc grpc.ClientConnInterface
}

func NewLaunchpadClient(cc grpc.ClientConnInterface) LaunchpadClient {
	return &launchpadClient{cc}
}

func (c *launchpadClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Launchpad_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, Launchpad_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) ListLaunchpads(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListLaunchpadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLaunchpadsResponse)
	err := c.cc.Invoke(ctx, Launchpad_ListLaunchpads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) CreateLaunchpad(ctx context.Context, in *CreateLaunchpadRequest, opts ...grpc.CallOption) (*LaunchpadInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchpadInfo)
	err := c.cc.Invoke(ctx, Launchpad_CreateLaunchpad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) GetLaunchpad(ctx context.Context, in *GetLaunchpadRequest, opts ...grpc.CallOption) (*LaunchpadInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchpadInfo)
	err := c.cc.Invoke(ctx, Launchpad_GetLaunchpad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) ListLaunchpadTokens(ctx context.Context, in *ListLaunchpadTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTokensResponse)
	err := c.cc.Invoke(ctx, Launchpad_ListLaunchpadTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTokensResponse)
	err := c.cc.Invoke(ctx, Launchpad_ListTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*Token, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Token)
	err := c.cc.Invoke(ctx, Launchpad_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, Launchpad_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) PrepareLaunch(ctx context.Context, in *PrepareLaunchRequest, opts ...grpc.CallOption) (*PreparedTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparedTransaction)
	err := c.cc.Invoke(ctx, Launchpad_PrepareLaunch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) QuoteSwap(ctx context.Context, in *QuoteSwapRequest, opts ...grpc.CallOption) (*QuoteSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteSwapResponse)
	err := c.cc.Invoke(ctx, Launchpad_QuoteSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) PrepareSwap(ctx context.Context, in *PrepareSwapRequest, opts ...grpc.CallOption) (*PreparedTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparedTransaction)
	err := c.cc.Invoke(ctx, Launchpad_PrepareSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) PrepareFeeClaim(ctx context.Context, in *PrepareFeeClaimRequest, opts ...grpc.CallOption) (*PreparedTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparedTransaction)
	err := c.cc.Invoke(ctx, Launchpad_PrepareFeeClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) GetFees(ctx context.Context, in *GetFeesRequest, opts ...grpc.CallOption) (*GetFeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeesResponse)
	err := c.cc.Invoke(ctx, Launchpad_GetFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) CreateAuthChallenge(ctx context.Context, in *CreateAuthChallengeRequest, opts ...grpc.CallOption) (*CreateAuthChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAuthChallengeResponse)
	err := c.cc.Invoke(ctx, Launchpad_CreateAuthChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) VerifyAuthSignature(ctx context.Context, in *VerifyAuthSignatureRequest, opts ...grpc.CallOption) (*VerifyAuthSignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAuthSignatureResponse)
	err := c.cc.Invoke(ctx, Launchpad_VerifyAuthSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaunchpadServer is the server API for Launchpad service.
// All implementations must embed UnimplementedLaunchpadServer
// for forward compatibility.
type LaunchpadServer interface {
	Health(context.Context, *Empty) (*HealthResponse, error)
	GetConfig(context.Context, *Empty) (*GetConfigResponse, error)
	ListLaunchpads(context.Context, *PageRequest) (*ListLaunchpadsResponse, error)
	CreateLaunchpad(context.Context, *CreateLaunchpadRequest) (*LaunchpadInfo, error)
	GetLaunchpad(context.Context, *GetLaunchpadRequest) (*LaunchpadInfo, error)
	ListLaunchpadTokens(context.Context, *ListLaunchpadTokensRequest) (*ListTokensResponse, error)
	ListTokens(context.Context, *ListTokensRequest) (*ListTokensResponse, error)
	GetToken(context.Context, *GetTokenRequest) (*Token, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error)
	PrepareLaunch(context.Context, *PrepareLaunchRequest) (*PreparedTransaction, error)
	QuoteSwap(context.Context, *QuoteSwapRequest) (*QuoteSwapResponse, error)
	PrepareSwap(context.Context, *PrepareSwapRequest) (*PreparedTransaction, error)
	PrepareFeeClaim(context.Context, *PrepareFeeClaimRequest) (*PreparedTransaction, error)
	GetFees(context.Context, *GetFeesRequest) (*GetFeesResponse, error)
	CreateAuthChallenge(context.Context, *CreateAuthChallengeRequest) (*CreateAuthChallengeResponse, error)
	VerifyAuthSignature(context.Context, *VerifyAuthSignatureRequest) (*VerifyAuthSignatureResponse, error)
	mustEmbedUnimplementedLaunchpadServer()
}

// UnimplementedLaunchpadServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLaunchpadServer struct{}

func (UnimplementedLaunchpadServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLaunchpadServer) GetConfig(context.Context, *Empty) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedLaunchpadServer) ListLaunchpads(context.Context, *PageRequest) (*ListLaunchpadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLaunchpads not implemented")
}
func (UnimplementedLaunchpadServer) CreateLaunchpad(context.Context, *CreateLaunchpadRequest) (*LaunchpadInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLaunchpad not implemented")
}
func (UnimplementedLaunchpadServer) GetLaunchpad(context.Context, *GetLaunchpadRequest) (*LaunchpadInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLaunchpad not implemented")
}
func (UnimplementedLaunchpadServer) ListLaunchpadTokens(context.Context, *ListLaunchpadTokensRequest) (*ListTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLaunchpadTokens not implemented")
}
func (UnimplementedLaunchpadServer) ListTokens(context.Context, *ListTokensRequest) (*ListTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTokens not implemented")
}
func (UnimplementedLaunchpadServer) GetToken(context.Context, *GetTokenRequest) (*Token, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedLaunchpadServer) GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedLaunchpadServer) PrepareLaunch(context.Context, *PrepareLaunchRequest) (*PreparedTransaction, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareLaunch not implemented")
}
func (UnimplementedLaunchpadServer) QuoteSwap(context.Context, *QuoteSwapRequest) (*QuoteSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuoteSwap not implemented")
}
func (UnimplementedLaunchpadServer) PrepareSwap(context.Context, *PrepareSwapRequest) (*PreparedTransaction, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareSwap not implemented")
}
func (UnimplementedLaunchpadServer) PrepareFeeClaim(context.Context, *PrepareFeeClaimRequest) (*PreparedTransaction, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareFeeClaim not implemented")
}
func (UnimplementedLaunchpadServer) GetFees(context.Context, *GetFeesRequest) (*GetFeesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFees not implemented")
}
func (UnimplementedLaunchpadServer) CreateAuthChallenge(context.Context, *CreateAuthChallengeRequest) (*CreateAuthChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuthChallenge not implemented")
}
func (UnimplementedLaunchpadServer) VerifyAuthSignature(context.Context, *VerifyAuthSignatureRequest) (*VerifyAuthSignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAuthSignature not implemented")
}
func (UnimplementedLaunchpadServer) mustEmbedUnimplementedLaunchpadServer() {}
func (UnimplementedLaunchpadServer) testEmbeddedByValue()                   {}

// UnsafeLaunchpadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaunchpadServer will
// result in compilation errors.
type UnsafeLaunchpadServer interface {
	mustEmbedUnimplementedLaunchpadServer()
}

func RegisterLaunchpadServer(s grpc.ServiceRegistrar, srv LaunchpadServer) {
	// If the following call panics, it indicates UnimplementedLaunchpadServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Launchpad_ServiceDesc, srv)
}

func _Launchpad_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).GetConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_ListLaunchpads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).ListLaunchpads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_ListLaunchpads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).ListLaunchpads(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_CreateLaunchpad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLaunchpadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).CreateLaunchpad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_CreateLaunchpad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).CreateLaunchpad(ctx, req.(*CreateLaunchpadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_GetLaunchpad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLaunchpadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).GetLaunchpad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_GetLaunchpad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).GetLaunchpad(ctx, req.(*GetLaunchpadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_ListLaunchpadTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLaunchpadTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).ListLaunchpadTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_ListLaunchpadTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).ListLaunchpadTokens(ctx, req.(*ListLaunchpadTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_ListTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).ListTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_ListTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).ListTokens(ctx, req.(*ListTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_PrepareLaunch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareLaunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).PrepareLaunch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_PrepareLaunch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).PrepareLaunch(ctx, req.(*PrepareLaunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_QuoteSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).QuoteSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_QuoteSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).QuoteSwap(ctx, req.(*QuoteSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_PrepareSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).PrepareSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_PrepareSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).PrepareSwap(ctx, req.(*PrepareSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_PrepareFeeClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareFeeClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).PrepareFeeClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_PrepareFeeClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).PrepareFeeClaim(ctx, req.(*PrepareFeeClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_GetFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).GetFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_GetFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).GetFees(ctx, req.(*GetFeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_CreateAuthChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).CreateAuthChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_CreateAuthChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).CreateAuthChallenge(ctx, req.(*CreateAuthChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_VerifyAuthSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAuthSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).VerifyAuthSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_VerifyAuthSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).VerifyAuthSignature(ctx, req.(*VerifyAuthSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Launchpad_ServiceDesc is the grpc.ServiceDesc for Launchpad service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Launchpad_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "launchpad.Launchpad",
	HandlerType: (*LaunchpadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Launchpad_Health_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Launchpad_GetConfig_Handler,
		},
		{
			MethodName: "ListLaunchpads",
			Handler:    _Launchpad_ListLaunchpads_Handler,
		},
		{
			MethodName: "CreateLaunchpad",
			Handler:    _Launchpad_CreateLaunchpad_Handler,
		},
		{
			MethodName: "GetLaunchpad",
			Handler:    _Launchpad_GetLaunchpad_Handler,
		},
		{
			MethodName: "ListLaunchpadTokens",
			Handler:    _Launchpad_ListLaunchpadTokens_Handler,
		},
		{
			MethodName: "ListTokens",
			Handler:    _Launchpad_ListTokens_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _Launchpad_GetToken_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _Launchpad_GetTransaction_Handler,
		},
		{
			MethodName: "PrepareLaunch",
			Handler:    _Launchpad_PrepareLaunch_Handler,
		},
		{
			MethodName: "QuoteSwap",
			Handler:    _Launchpad_QuoteSwap_Handler,
		},
		{
			MethodName: "PrepareSwap",
			Handler:    _Launchpad_PrepareSwap_Handler,
		},
		{
			MethodName: "PrepareFeeClaim",
			Handler:    _Launchpad_PrepareFeeClaim_Handler,
		},
		{
			MethodName: "GetFees",
			Handler:    _Launchpad_GetFees_Handler,
		},
		{
			MethodName: "CreateAuthChallenge",
			Handler:    _Launchpad_CreateAuthChallenge_Handler,
		},
		{
			MethodName: "VerifyAuthSignature",
			Handler:    _Launchpad_VerifyAuthSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "launchpad.proto",
}
