// Code generated by goctl. DO NOT EDIT.
// Source: launchpad.proto

package server

import (
	"context"

	"o1-launchpad/service/launchpad/rpc/internal/logic"
	"o1-launchpad/service/launchpad/rpc/internal/svc"
	"o1-launchpad/service/launchpad/rpc/pb/launchpad"
)

type LaunchpadServer struct {
	svcCtx *svc.ServiceContext
	launchpad.UnimplementedLaunchpadServer
}

func NewLaunchpadServer(svcCtx *svc.ServiceContext) *LaunchpadServer {
	return &LaunchpadServer{
		svcCtx: svcCtx,
	}
}

func (s *LaunchpadServer) Health(ctx context.Context, in *launchpad.Empty) (*launchpad.HealthResponse, error) {
	l := logic.NewHealthLogic(ctx, s.svcCtx)
	return l.Health(in)
}

func (s *LaunchpadServer) GetConfig(ctx context.Context, in *launchpad.Empty) (*launchpad.GetConfigResponse, error) {
	l := logic.NewGetConfigLogic(ctx, s.svcCtx)
	return l.GetConfig(in)
}

func (s *LaunchpadServer) ListLaunchpads(ctx context.Context, in *launchpad.PageRequest) (*launchpad.ListLaunchpadsResponse, error) {
	l := logic.NewListLaunchpadsLogic(ctx, s.svcCtx)
	return l.ListLaunchpads(in)
}

func (s *LaunchpadServer) CreateLaunchpad(ctx context.Context, in *launchpad.CreateLaunchpadRequest) (*launchpad.LaunchpadInfo, error) {
	l := logic.NewCreateLaunchpadLogic(ctx, s.svcCtx)
	return l.CreateLaunchpad(in)
}

func (s *LaunchpadServer) GetLaunchpad(ctx context.Context, in *launchpad.GetLaunchpadRequest) (*launchpad.LaunchpadInfo, error) {
	l := logic.NewGetLaunchpadLogic(ctx, s.svcCtx)
	return l.GetLaunchpad(in)
}

func (s *LaunchpadServer) ListLaunchpadTokens(ctx context.Context, in *launchpad.ListLaunchpadTokensRequest) (*launchpad.ListTokensResponse, error) {
	l := logic.NewListLaunchpadTokensLogic(ctx, s.svcCtx)
	return l.ListLaunchpadTokens(in)
}

func (s *LaunchpadServer) ListTokens(ctx context.Context, in *launchpad.ListTokensRequest) (*launchpad.ListTokensResponse, error) {
	l := logic.NewListTokensLogic(ctx, s.svcCtx)
	return l.ListTokens(in)
}

func (s *LaunchpadServer) GetToken(ctx context.Context, in *launchpad.GetTokenRequest) (*launchpad.Token, error) {
	l := logic.NewGetTokenLogic(ctx, s.svcCtx)
	return l.GetToken(in)
}

func (s *LaunchpadServer) GetTransaction(ctx context.Context, in *launchpad.GetTransactionRequest) (*launchpad.Transaction, error) {
	l := logic.NewGetTransactionLogic(ctx, s.svcCtx)
	return l.GetTransaction(in)
}

func (s *LaunchpadServer) PrepareLaunch(ctx context.Context, in *launchpad.PrepareLaunchRequest) (*launchpad.PreparedTransaction, error) {
	l := logic.NewPrepareLaunchLogic(ctx, s.svcCtx)
	return l.PrepareLaunch(in)
}

func (s *LaunchpadServer) QuoteSwap(ctx context.Context, in *launchpad.QuoteSwapRequest) (*launchpad.QuoteSwapResponse, error) {
	l := logic.NewQuoteSwapLogic(ctx, s.svcCtx)
	return l.QuoteSwap(in)
}

func (s *LaunchpadServer) PrepareSwap(ctx context.Context, in *launchpad.PrepareSwapRequest) (*launchpad.PreparedTransaction, error) {
	l := logic.NewPrepareSwapLogic(ctx, s.svcCtx)
	return l.PrepareSwap(in)
}

func (s *LaunchpadServer) PrepareFeeClaim(ctx context.Context, in *launchpad.PrepareFeeClaimRequest) (*launchpad.PreparedTransaction, error) {
	l := logic.NewPrepareFeeClaimLogic(ctx, s.svcCtx)
	return l.PrepareFeeClaim(in)
}

func (s *LaunchpadServer) GetFees(ctx context.Context, in *launchpad.GetFeesRequest) (*launchpad.GetFeesResponse, error) {
	l := logic.NewGetFeesLogic(ctx, s.svcCtx)
	return l.GetFees(in)
}

func (s *LaunchpadServer) CreateAuthChallenge(ctx context.Context, in *launchpad.CreateAuthChallengeRequest) (*launchpad.CreateAuthChallengeResponse, error) {
	l := logic.NewCreateAuthChallengeLogic(ctx, s.svcCtx)
	return l.CreateAuthChallenge(in)
}

func (s *LaunchpadServer) VerifyAuthSignature(ctx context.Context, in *launchpad.VerifyAuthSignatureRequest) (*launchpad.VerifyAuthSignatureResponse, error) {
	l := logic.NewVerifyAuthSignatureLogic(ctx, s.svcCtx)
	return l.VerifyAuthSignature(in)
}
