// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "o1-launchpad/service/launchpad/api/internal/handler/auth"
	fee "o1-launchpad/service/launchpad/api/internal/handler/fee"
	launch "o1-launchpad/service/launchpad/api/internal/handler/launch"
	launchpad "o1-launchpad/service/launchpad/api/internal/handler/launchpad"
	swap "o1-launchpad/service/launchpad/api/internal/handler/swap"
	system "o1-launchpad/service/launchpad/api/internal/handler/system"
	token "o1-launchpad/service/launchpad/api/internal/handler/token"
	transaction "o1-launchpad/service/launchpad/api/internal/handler/transaction"
	"o1-launchpad/service/launchpad/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/challenge",
				Handler: auth.CreateAuthChallengeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/verify",
				Handler: auth.VerifyAuthSignatureHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/claims/fees/prepare",
				Handler: fee.PrepareFeeClaimHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/fees/:recipient",
				Handler: fee.GetFeesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/launches/prepare",
				Handler: launch.PrepareLaunchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/launchpads",
				Handler: launchpad.ListLaunchpadsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/launchpads/:slug",
				Handler: launchpad.GetLaunchpadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/launchpads/:slug/tokens",
				Handler: launchpad.ListLaunchpadTokensHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Session},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/launchpads",
					Handler: launchpad.CreateLaunchpadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/swaps/prepare",
				Handler: swap.PrepareSwapHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/swaps/quote",
				Handler: swap.QuoteSwapHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/config",
				Handler: system.GetConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: system.HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health/live",
				Handler: system.LiveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/ready",
				Handler: system.ReadyHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tokens",
				Handler: token.ListTokensHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tokens/:chain_id/:token_address",
				Handler: token.GetTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/transactions/:chain_id/:tx_hash",
				Handler: transaction.GetTransactionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
