// Code generated by goctl. DO NOT EDIT.
package types

type ConfigResponse struct {
	ChainId       int64  `json:"chain_id"`
	Registry      string `json:"registry"`
	Factory       string `json:"factory"`
	Hook          string `json:"hook"`
	FeeEscrow     string `json:"fee_escrow"`
	Quote         string `json:"quote"`
	ConfigVersion uint64 `json:"config_version"`
}

type CreateAuthChallengeRequest struct {
	ChainId int64  `json:"chain_id"`
	Address string `json:"address"`
	Domain  string `json:"domain"`
	Uri     string `json:"uri"`
}

type CreateAuthChallengeResponse struct {
	ChallengeId string `json:"challenge_id"`
	Message     string `json:"message"`
	ExpiresAt   string `json:"expires_at"`
}

type CreateLaunchpadRequest struct {
	ChainId        int64  `json:"chain_id"`
	Slug           string `json:"slug"`
	Name           string `json:"name"`
	Description    string `json:"description,optional"`
	LogoUrl        string `json:"logo_url,optional"`
	PrimaryColor   string `json:"primary_color,optional"`
	RegistryTxHash string `json:"registry_tx_hash"`
}

type HealthResponse struct {
	Status string `json:"status"`
}

type LaunchpadInfo struct {
	Id           string `json:"id"`
	ChainId      int64  `json:"chain_id"`
	Slug         string `json:"slug"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	LogoUrl      string `json:"logo_url"`
	PrimaryColor string `json:"primary_color"`
	Owner        string `json:"owner"`
	Treasury     string `json:"treasury"`
	Active       bool   `json:"active"`
	CreatedAt    string `json:"created_at"`
}

type LaunchpadPath struct {
	Slug string `path:"slug"`
}

type ListLaunchpadTokensRequest struct {
	Slug   string `path:"slug"`
	Limit  uint32 `form:"limit,optional"`
	Cursor string `form:"cursor,optional"`
}

type ListLaunchpadsResponse struct {
	Launchpads []LaunchpadInfo `json:"launchpads"`
	NextCursor string          `json:"next_cursor"`
}

type ListTokensResponse struct {
	Tokens     []TokenInfo `json:"tokens"`
	NextCursor string      `json:"next_cursor"`
}

type PageRequest struct {
	Limit  uint32 `form:"limit,optional"`
	Cursor string `form:"cursor,optional"`
}

type PrepareFeeClaimRequest struct {
	ChainId   int64  `json:"chain_id"`
	Currency  string `json:"currency"`
	Recipient string `json:"recipient"`
	Wallet    string `json:"wallet"`
}

type PrepareLaunchRequest struct {
	ChainId     int64  `json:"chain_id"`
	LaunchpadId string `json:"launchpad_id"`
	Name        string `json:"name"`
	Symbol      string `json:"symbol"`
	ContractUri string `json:"contract_uri,optional"`
	Salt        string `json:"salt"`
	Wallet      string `json:"wallet"`
}

type PrepareSwapRequest struct {
	ChainId     int64  `json:"chain_id"`
	QuoteId     string `json:"quote_id"`
	SlippageBps uint32 `json:"slippage_bps"`
	Wallet      string `json:"wallet"`
}

type PreparedTransaction struct {
	ChainId  int64  `json:"chain_id"`
	To       string `json:"to"`
	Data     string `json:"data"`
	Value    string `json:"value"`
	Deadline uint64 `json:"deadline"`
}

type QuoteSwapRequest struct {
	ChainId  int64  `json:"chain_id"`
	Token    string `json:"token"`
	Amount   string `json:"amount"`
	Buy      bool   `json:"buy"`
	Wallet   string `json:"wallet"`
	Referrer string `json:"referrer,optional"`
}

type QuoteSwapResponse struct {
	QuoteId   string `json:"quote_id"`
	AmountIn  string `json:"amount_in"`
	AmountOut string `json:"amount_out"`
	Fee       string `json:"fee"`
	ExpiresAt uint64 `json:"expires_at"`
}

type TokenInfo struct {
	ChainId       int64  `json:"chain_id"`
	Token         string `json:"token"`
	PoolId        string `json:"pool_id"`
	LaunchpadId   string `json:"launchpad_id"`
	LaunchpadSlug string `json:"launchpad_slug"`
	Creator       string `json:"creator"`
	Quote         string `json:"quote"`
	Supply        string `json:"supply"`
	TxHash        string `json:"tx_hash"`
	BlockNumber   uint64 `json:"block_number"`
	Status        string `json:"status"`
	CreatedAt     string `json:"created_at"`
}

type TokenPath struct {
	ChainId      int64  `path:"chain_id"`
	TokenAddress string `path:"token_address"`
}

type TransactionInfo struct {
	ChainId       int64  `json:"chain_id"`
	TxHash        string `json:"tx_hash"`
	Kind          string `json:"kind"`
	Status        string `json:"status"`
	BlockNumber   uint64 `json:"block_number"`
	FailureReason string `json:"failure_reason"`
	UpdatedAt     string `json:"updated_at"`
}

type TransactionPath struct {
	ChainId int64  `path:"chain_id"`
	TxHash  string `path:"tx_hash"`
}

type VerifyAuthSignatureRequest struct {
	ChallengeId string `json:"challenge_id"`
	Address     string `json:"address"`
	Signature   string `json:"signature"`
}

type VerifyAuthSignatureResponse struct {
	Address   string `json:"address"`
	ExpiresAt string `json:"expires_at"`
}
