// Code generated by goctl. DO NOT EDIT.
// Source: launchpad.proto

package launchpadclient

import (
	"context"

	"o1-launchpad/service/launchpad/rpc/pb/launchpad"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAuthChallengeRequest  = launchpad.CreateAuthChallengeRequest
	CreateAuthChallengeResponse = launchpad.CreateAuthChallengeResponse
	CreateLaunchpadRequest      = launchpad.CreateLaunchpadRequest
	Empty                       = launchpad.Empty
	GetConfigResponse           = launchpad.GetConfigResponse
	GetFeesRequest              = launchpad.GetFeesRequest
	GetFeesResponse             = launchpad.GetFeesResponse
	GetLaunchpadRequest         = launchpad.GetLaunchpadRequest
	GetTokenRequest             = launchpad.GetTokenRequest
	GetTransactionRequest       = launchpad.GetTransactionRequest
	HealthResponse              = launchpad.HealthResponse
	LaunchpadInfo               = launchpad.LaunchpadInfo
	ListLaunchpadTokensRequest  = launchpad.ListLaunchpadTokensRequest
	ListLaunchpadsResponse      = launchpad.ListLaunchpadsResponse
	ListTokensRequest           = launchpad.ListTokensRequest
	ListTokensResponse          = launchpad.ListTokensResponse
	PageRequest                 = launchpad.PageRequest
	PrepareFeeClaimRequest      = launchpad.PrepareFeeClaimRequest
	PrepareLaunchRequest        = launchpad.PrepareLaunchRequest
	PrepareSwapRequest          = launchpad.PrepareSwapRequest
	PreparedTransaction         = launchpad.PreparedTransaction
	QuoteSwapRequest            = launchpad.QuoteSwapRequest
	QuoteSwapResponse           = launchpad.QuoteSwapResponse
	Token                       = launchpad.Token
	Transaction                 = launchpad.Transaction
	VerifyAuthSignatureRequest  = launchpad.VerifyAuthSignatureRequest
	VerifyAuthSignatureResponse = launchpad.VerifyAuthSignatureResponse

	Launchpad interface {
		Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
		GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConfigResponse, error)
		ListLaunchpads(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListLaunchpadsResponse, error)
		CreateLaunchpad(ctx context.Context, in *CreateLaunchpadRequest, opts ...grpc.CallOption) (*LaunchpadInfo, error)
		GetLaunchpad(ctx context.Context, in *GetLaunchpadRequest, opts ...grpc.CallOption) (*LaunchpadInfo, error)
		ListLaunchpadTokens(ctx context.Context, in *ListLaunchpadTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error)
		ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error)
		GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*Token, error)
		GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
		PrepareLaunch(ctx context.Context, in *PrepareLaunchRequest, opts ...grpc.CallOption) (*PreparedTransaction, error)
		QuoteSwap(ctx context.Context, in *QuoteSwapRequest, opts ...grpc.CallOption) (*QuoteSwapResponse, error)
		PrepareSwap(ctx context.Context, in *PrepareSwapRequest, opts ...grpc.CallOption) (*PreparedTransaction, error)
		PrepareFeeClaim(ctx context.Context, in *PrepareFeeClaimRequest, opts ...grpc.CallOption) (*PreparedTransaction, error)
		GetFees(ctx context.Context, in *GetFeesRequest, opts ...grpc.CallOption) (*GetFeesResponse, error)
		CreateAuthChallenge(ctx context.Context, in *CreateAuthChallengeRequest, opts ...grpc.CallOption) (*CreateAuthChallengeResponse, error)
		VerifyAuthSignature(ctx context.Context, in *VerifyAuthSignatureRequest, opts ...grpc.CallOption) (*VerifyAuthSignatureResponse, error)
	}

	defaultLaunchpad struct {
		cli zrpc.Client
	}
)

func NewLaunchpad(cli zrpc.Client) Launchpad {
	return &defaultLaunchpad{
		cli: cli,
	}
}

func (m *defaultLaunchpad) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.Health(ctx, in, opts...)
}

func (m *defaultLaunchpad) GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.GetConfig(ctx, in, opts...)
}

func (m *defaultLaunchpad) ListLaunchpads(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListLaunchpadsResponse, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.ListLaunchpads(ctx, in, opts...)
}

func (m *defaultLaunchpad) CreateLaunchpad(ctx context.Context, in *CreateLaunchpadRequest, opts ...grpc.CallOption) (*LaunchpadInfo, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.CreateLaunchpad(ctx, in, opts...)
}

func (m *defaultLaunchpad) GetLaunchpad(ctx context.Context, in *GetLaunchpadRequest, opts ...grpc.CallOption) (*LaunchpadInfo, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.GetLaunchpad(ctx, in, opts...)
}

func (m *defaultLaunchpad) ListLaunchpadTokens(ctx context.Context, in *ListLaunchpadTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.ListLaunchpadTokens(ctx, in, opts...)
}

func (m *defaultLaunchpad) ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.ListTokens(ctx, in, opts...)
}

func (m *defaultLaunchpad) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*Token, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.GetToken(ctx, in, opts...)
}

func (m *defaultLaunchpad) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.GetTransaction(ctx, in, opts...)
}

func (m *defaultLaunchpad) PrepareLaunch(ctx context.Context, in *PrepareLaunchRequest, opts ...grpc.CallOption) (*PreparedTransaction, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.PrepareLaunch(ctx, in, opts...)
}

func (m *defaultLaunchpad) QuoteSwap(ctx context.Context, in *QuoteSwapRequest, opts ...grpc.CallOption) (*QuoteSwapResponse, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.QuoteSwap(ctx, in, opts...)
}

func (m *defaultLaunchpad) PrepareSwap(ctx context.Context, in *PrepareSwapRequest, opts ...grpc.CallOption) (*PreparedTransaction, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.PrepareSwap(ctx, in, opts...)
}

func (m *defaultLaunchpad) PrepareFeeClaim(ctx context.Context, in *PrepareFeeClaimRequest, opts ...grpc.CallOption) (*PreparedTransaction, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.PrepareFeeClaim(ctx, in, opts...)
}

func (m *defaultLaunchpad) GetFees(ctx context.Context, in *GetFeesRequest, opts ...grpc.CallOption) (*GetFeesResponse, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.GetFees(ctx, in, opts...)
}

func (m *defaultLaunchpad) CreateAuthChallenge(ctx context.Context, in *CreateAuthChallengeRequest, opts ...grpc.CallOption) (*CreateAuthChallengeResponse, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.CreateAuthChallenge(ctx, in, opts...)
}

func (m *defaultLaunchpad) VerifyAuthSignature(ctx context.Context, in *VerifyAuthSignatureRequest, opts ...grpc.CallOption) (*VerifyAuthSignatureResponse, error) {
	client := launchpad.NewLaunchpadClient(m.cli.Conn())
	return client.VerifyAuthSignature(ctx, in, opts...)
}
